### ISSUE TITLE
Where should i config the database parameters like dbhost, dbname, dbuser, dbpass?

### ISSUE THREAD

**Issue by javasworks** [nilportugues/sql-query-builder#70]
I didn't see it in the documentation. So, How's the proper way to set these db config?

**Comment by nilopc** [comment]
It's a query builder, so there's no need to establish a database connection at all. 

You may use pdo or mysqli as you normally use, write the query with the query builder, and pass the values to the pdo or mysqli method to run the query.

Maybe I should write a how to use section after all :+1:
